name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ master, .* ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create docker buildx builder
        shell: bash
        run: docker buildx create --use

      - name: Build and push docker image
        shell: bash
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/apono-io/git2consul:${{ github.sha }} --push .
